#!/bin/sh
set -e
cargo fmt -- --check || (echo 'To fix, run: cargo fmt' && false)
#cargo test --features=float-as-double,sampled-spectrum --quiet
# TODO(wathiede): reenable sampled-spectrum when it's ready.
cargo test --features=float-as-double --quiet
FILES_AFFECTED=$(git diff-index --name-only --cached --diff-filter=AMR HEAD|xargs)
if [ ! -z "${FILES_AFFECTED}" ]; then
  scripts/insert.py --presubmit ${FILES_AFFECTED:?}
fi
