[package]
name = "pbrt"
version = "0.1.1"
authors = ["Bill Thiede <rust@xinu.tv>"]
license = "Apache-2.0"
readme = "README.md"
description = "Rust implementation of https://pbrt.org/"
repository = "https://github.com/wathiede/pbrt"

[dependencies]
nom = "3.2.1"
regex = "0.2.5"
log = "0.4.1"

[dev-dependencies]
pretty_assertions = "0.5.0"
