[package]
authors = ["Bill Thiede <rust@xinu.tv>"]
description = "Rust implementation of https://pbrt.org/"
edition = "2018"
license = "Apache-2.0"
name = "pbrt"
readme = "README.md"
repository = "https://github.com/wathiede/pbrt"
version = "0.1.6-alpha.0"
[dependencies]
log = "0.4.1"
nom = "3.2.1"
image = "0.22.3"
regex = "0.2.5"
simplelog = "0.4.4"
structopt = "0.3.5"

[dev-dependencies]
pretty_assertions = "0.5.0"
rayon = "1.2.1"

[features]
float-as-double = []
sampled-spectrum = []
uble = []
