[package]
authors = ["Bill Thiede <rust@xinu.tv>"]
description = "Rust implementation of https://pbrt.org/"
edition = "2018"
license = "Apache-2.0"
name = "pbrt"
readme = "README.md"
repository = "https://github.com/wathiede/pbrt"
version = "0.1.6-alpha.0"
[dependencies]
log = "0.4.20"
image = "0.24.7"
regex = "1.10.2"
structopt = "0.3.26"
thiserror = "1.0.57"
stderrlog = "0.5.4"
anyhow = "1.0.78"
memmap = "0.7.0"
lazy_static = "1.4.0"
assert_approx_eq = "1.1.0"

[dev-dependencies]
pretty_assertions = "1.4.0"
rayon = "1.8.0"
tempfile = "3.9.0"

[features]
float-as-double = []
sampled-spectrum = []
